#!/usr/bin/env python3
"""Generate pkg/constants/constants.go from sky/skylet/constants.py.

Run from any directory; paths are resolved relative to this script.
"""
import os
import re

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
_CONSTANTS_PY = os.path.normpath(
    os.path.join(_SCRIPT_DIR, '..', '..', '..', 'constants.py'))
_OUTPUT_GO = os.path.normpath(
    os.path.join(_SCRIPT_DIR, '..', 'pkg', 'constants', 'constants.go'))

# Maps Python name → (Go name, doc comment).
_EXTRACT = {
    'SKY_AGENT_PORT': (
        'AgentPort',
        'AgentPort is the default gRPC port that sky-agent listens on.',
    ),
    'SKYLET_GRPC_PORT': (
        'SkyletPort',
        'SkyletPort is the gRPC port of the skylet JobsService on the head node.',
    ),
}


def _parse(path: str) -> dict:
    values = {}
    with open(path, encoding='utf-8') as f:
        for line in f:
            for py_name, (go_name, _) in _EXTRACT.items():
                m = re.match(rf'^{py_name}\s*=\s*(\d+)', line)
                if m:
                    values[go_name] = int(m.group(1))
    missing = [
        py for py, (go, _) in _EXTRACT.items() if go not in values
    ]
    if missing:
        raise ValueError(f'Could not find constants in {path}: {missing}')
    return values


def _generate(values: dict) -> str:
    lines = [
        '// Code generated by scripts/gen_go_constants.py. DO NOT EDIT.',
        '// Source of truth: sky/skylet/constants.py',
        'package constants',
        '',
        'const (',
    ]
    for py_name, (go_name, doc) in _EXTRACT.items():
        lines.append(f'\t// {doc}')
        lines.append(f'\t// Must stay in sync with {py_name} in sky/skylet/constants.py.')
        lines.append(f'\t{go_name} = {values[go_name]}')
        lines.append('')
    lines.append(')')
    return '\n'.join(lines) + '\n'


def main() -> None:
    values = _parse(_CONSTANTS_PY)
    os.makedirs(os.path.dirname(_OUTPUT_GO), exist_ok=True)
    content = _generate(values)
    with open(_OUTPUT_GO, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f'Generated {_OUTPUT_GO}')


if __name__ == '__main__':
    main()
