// Code generated by scripts/gen_go_constants.py. DO NOT EDIT.
// Source of truth: sky/skylet/constants.py
package constants

const (
	// AgentPort is the default gRPC port that sky-agent listens on.
	// Must stay in sync with SKY_AGENT_PORT in sky/skylet/constants.py.
	AgentPort = 50052

	// SkyletPort is the gRPC port of the skylet JobsService on the head node.
	// Must stay in sync with SKYLET_GRPC_PORT in sky/skylet/constants.py.
	SkyletPort = 46590

)
